# Generated by Django 3.0.3 on 2020-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20200302_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
