# Generated by Django 3.0.3 on 2020-03-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.TaskList')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.Task')),
            ],
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(related_name='lists', through='tasker.TaskMembership', to='tasker.Task'),
        ),
    ]
